[package]
name = "zookeeper-client"
version = "0.1.2"
edition = "2021"
authors = ["Kezhu Wang <kezhuw@gmail.com>"]
description = "ZooKeeper async client"
repository = "https://github.com/kezhuw/zookeeper-client-rust/"
license-file = "LICENSE"
keywords = ["ZooKeeper"]
categories = ["api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
tokio = {version = "1.15.0", features = ["full"]}
thiserror = "1.0.30"
strum = { version = "0.23", features = ["derive"] }
num_enum = "0.5.6"
ignore-result = "0.2.0"
compact_str = "0.2.0"
const_format = "0.2.22"
log = "0.4.14"

[dev-dependencies]
rand = "0.8.4"
pretty_assertions = "1.1.0"
test-case = "1.2.3"
testcontainers = "0.12.0"
